GET http://localhost:3004/recipe/chicken-fettuccine
###

GET http://localhost:3004/recipe/onion-pasta
###

GET http://localhost:3004/recipe/chicken-noodle-soup
###

GET http://localhost:3004/recipe/scallion-oil-noodle
###

GET http://localhost:3004/recipe/a
###