export const recipes = {
  recipe: [
    {
      title: "Chicken Fettuccine",
      preptime: "25 minutes",
      servings: "4 servings",
      ingredients: [
        "Kosher salt and freshly ground black pepper",
        "12 ounces fettuccine",
        "Olive oil, for tossing",
        "12 ounces boneless, skinless chicken breast (about 2) ",
        "1 stick (8 tablespoons) unsalted butter",
        "2 cups heavy cream",
        "12 pinches freshly grated nutmeg",
        "1 1/2 cups freshly grated Parmigiano-Reggiano",
      ],
      image: "../chicken-fettuccine.jpeg",
      imagealt: "chicken-fettuccine",
      instructions: [
        "Bring a large pot of water to a boil, and salt generously. Add the pasta and cook according to package directions until al dente (tender but still slightly firm). Drain and toss with a splash of oil.",
        "Meanwhile, slice the chicken into 1/4-inch-thick strips, and lay them on a plate or a sheet of waxed paper. Season with salt and pepper.",
        "Heat a large skillet over medium heat. Add 2 tablespoons of the butter. When the butter melts, raise the heat to medium-high and add the chicken in 1 layer. Cook, without moving the pieces, until the underside has browned, 1 to 2 minutes. Flip the pieces, and cook until browned and cooked through, 2 to 3 minutes more. Transfer the chicken to a medium bowl.",
        "Reduce the heat to medium. Add the remaining 6 tablespoons butter. Scrape the bottom of the skillet with a wooden spoon to release any browned bits. When the butter has mostly melted, whisk in the cream and nutmeg and bring to a simmer, then cook for 2 minutes. Lower the heat to keep the sauce just warm.",
        "Whisk the Parmigiano-Reggiano into the sauce. Add the chicken and cooked pasta and toss well. Season with salt and pepper. Serve hot in heated bowls.",
      ],
    },
    {
      title: "Onion Pasta",
      preptime: "55 minutes",
      servings: "4 servings",
      ingredients: [
        "2 Tbsp. extra-virgin olive oil",
        "2 Tbsp. unsalted butter",
        "2 lb. onions (about 3 large), thinly sliced",
        "2 garlic cloves, thinly sliced",
        "1/4 tsp. crushed red pepper flakes (optional)",
        "1 1/2 tsp. kosher salt, plus more",
        "12 oz. linguine or other long pasta",
        "4 oz. Parmesan, finely grated (about 1 cup), divided, plus more for serving",
        "½ cup parsley, finely chopped (optional), plus more for serving",
        "Freshly ground black pepper",
      ],
      image: "../caramelized-onion-pasta.jpeg",
      imagealt: "caramelized-onion-pasta",
      instructions: [
        "Heat oil and butter in a large heavy pot or Dutch oven over medium until butter is melted. Add onions and garlic and cook, stirring occasionally, until very tender and deeply golden brown, about 30 minutes. (Stop before the onions become dry and shriveled.) Add red pepper flakes (if using) and 1 1/2 tsp. salt. Remove pot from heat.",
        "Meanwhile, cook pasta in a large pot of boiling salted water, stirring occasionally, until al dente. Reserve 1 1/2 cups pasta cooking liquid.",
        "Add pasta and 1 cup pasta cooking liquid to onion mixture and stir to combine. Add a small handful of cheese and stir until melted. Repeat with remaining cheese, adding more pasta cooking liquid as needed to create a glossy sauce that coats the pasta. Stir in parsley (if using).",
        "Divide pasta among bowls. Top with Parmesan, parsley, and a few cranks of pepper.",
      ],
    },
    {
      title: "Chicken Noodle Soup",
      preptime: "60 minutes",
      servings: "10 servings",
      ingredients: [
        "2-1/2 pounds bone-in chicken thighs",
        "1/2 teaspoon salt",
        "1/2 teaspoon pepper",
        "1 tablespoon canola oil",
        "1 large onion, chopped",
        "1 garlic clove, minced",
        "10 cups chicken broth",
        "4 celery ribs, chopped",
        "4 medium carrots, chopped",
        "2 bay leaves",
        "1 teaspoon minced fresh thyme or 1/4 teaspoon dried thyme",
        "3 cups uncooked kluski or other egg noodles (about 8 ounces)",
        "1 tablespoon chopped fresh parsley",
        "1 tablespoon lemon juice",
      ],
      image: "../chicken-noodle-soup.jpeg",
      imagealt: "chicken-noodle-soup",
      instructions: [
        "Pat chicken dry with paper towels; sprinkle with salt and pepper. In a 6-qt. stockpot, heat oil over medium-high heat. Add chicken in batches, skin side down; cook until dark golden brown, 3-4 minutes. Remove chicken from pan; remove and discard skin. Discard drippings, reserving 2 tablespoons.",
        "Add onion to drippings; cook and stir over medium-high heat until tender, 4-5 minutes. Add garlic; cook 1 minute longer. Add broth, stirring to loosen browned bits from pan. Bring to a boil. Return chicken to pan. Add celery, carrots, bay leaves and thyme. Reduce heat; simmer, covered, until chicken is tender, 25-30 minutes.",
        "Transfer chicken to a plate. Remove soup from heat. Add noodles; let stand, covered, until noodles are tender, 20-22 minutes.",
        "Meanwhile, when chicken is cool enough to handle, remove meat from bones; discard bones. Shred meat into bite-sized pieces. Return meat to stockpot. Stir in parsley and lemon juice. If desired, adjust seasoning with additional salt and pepper. Discard bay leaves.",
      ],
    },
    {
      title: "Scallion Oil Noodle",
      preptime: "30 minutes",
      servings: "10 servings",
      ingredients: [
        "1 to 2 large bunches of green onions",
        "1/4 cup neutral oil",
        "1 packed teaspoon organic dark brown sugar",
        "2 teaspoons organic cane (white) sugar",
        "1 tablespoon plus 2 teaspoons low-sodium soy sauce",
        "2 tablespoons regular soy sauce",
        "1 to 2 tablespoons chili crisp",
        "1 teaspoon white rice vinegar",
        "1 teaspoon Chinese black vinegar",
        "1 1/2 teaspoons chopped garlic (2 to 4 cloves)",
        "110 ounces soba noodles",
      ],
      image: "../scallion-oil-noodles.jpeg",
      imagealt: "scallion-oil-noodles",
      instructions: [
        "Cut the greens into roughly 4 pieces and then thinly slice them lengthwise.",
        "Thinly slice the whites lengthwise. You should end up with approximately 4 ounces (115 grams) of light greens/whites and 4 ounces (115 grams) of greens after prep.",
        "Heat an enameled sauté pan or large non-stick pan over medium-high (my temperature is on the low end of medium-high). Add the oil, heat until shimmering, then add the white parts of the onion. Toss to thoroughly coat then spread the onions out in an even layer. The onions should have a solid sizzle but if they start to brown too quickly lower the heat. Stir frequently.",
        "Turn the heat off, tip the pan, and using a large spoon drag the onions away from the oil and press them gently against the side of the pan. This will drain most of the oil off of the onion whites. Promptly transfer the onions to a plate and set aside.",
        "Return the heat to medium-high and add the greens. Cook using the same process as above. The greens take about 5 to 7 minutes depending on how thinly they're sliced. When finished, turn off the heat, transfer the greens to the plate with the whites, and set the pan with the remaining oil aside. (Don't discard the oil in the pan.)",
        "Heat a large pot of water for the noodles.",
        "While the water comes to a boil, whisk all of the sauce ingredients together (dark brown sugar, white sugar, soy sauces, chili crisp, vinegars, and garlic) and then add them to the pan with the scallion oil. Stir to combine and adjust the chili crisp as desired.",
        "Cook the noodles just shy of al dente.",
        "Transfer the cooked noodles to a mesh strainer and rinse immediately under cold water. Drain and set aside.",
        "Heat the scallion oil mixture over medium-high until warm to hot (the edges will just start to bubble) then add the drained noodles and half of the fried green onions (both greens and whites). Toss briskly to coat and incorporate. Continue to toss over medium-high until the sauce is mostly absorbed and the noodles are hot throughout. This process goes quickly - a minute or so.",
        "Plate and then divide the rest of the fried green onions between each dish.",
      ],
    },
  ],
};
